# Generated by Django 4.1.1 on 2022-10-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['last_name'], 'verbose_name': 'Именинник', 'verbose_name_plural': 'Именинники'},
        ),
        migrations.AlterField(
            model_name='congratulation',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Женский', max_length=9, verbose_name='Пол'),
        ),
    ]
